import os, sys, importlib.util, tempfile
from typing import Callable

# TUI imports
import threading, queue, time

if sys.platform == 'win32':
    import msvcrt
    # import ctypes
    # from ctypes import wintypes
else:
    import termios, tty #, select




UEFI_BRIDGE_NAME = 'uefi-ntfs.img'
UEFI_BRIDGE_DOWNLOAD_URL = f'https://raw.githubusercontent.com/pbatard/rufus/master/res/uefi/{UEFI_BRIDGE_NAME}'
DBX_REVOCATION_URL = 'https://raw.githubusercontent.com/microsoft/secureboot_objects/refs/heads/main/PreSignedObjects/DBX/dbx_info_msft_latest.json'


## -- Load Rust module

def _load_module(module_name: str, path: str):

    spec = importlib.util.spec_from_file_location(module_name, path)
    if spec and spec.loader:
        mod = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(mod)
        return mod
    return None


def _load_rust_pip_or_dev(_rust_lib_name: str = '_libiso', module_dev_path: str = None):
    
    # Wheel load (pip install)
    try:
        from . import _libiso
        return _libiso
    except ImportError:
        pass
    
    if os.name == 'nt':
        expected_file = f'{_rust_lib_name}.dll' 
    elif sys.platform == 'darwin':
        expected_file = f'lib{_rust_lib_name}.dylib'
    else:
        expected_file = f'lib{_rust_lib_name}.so'

    py_dir = __file__.replace('\\', '/').rsplit('/', 1)[0]
    root_dir = py_dir.rsplit('/', 1)[0]
    dev_path = module_dev_path or f'{root_dir}/target/release/{expected_file}'
    
    # Search local directory (for maturin develop)
    for file in os.listdir(py_dir):
        if ((file.startswith(f'lib{_rust_lib_name}') or file.startswith(_rust_lib_name)) 
                and file.endswith(('.so', '.pyd', '.dylib', '.dll'))):
            mod = _load_module(_rust_lib_name, f'{py_dir}/{file}')
            if mod: return mod
    
    # Maturin build in CI
    if os.path.exists(dev_path):
        mod = _load_module(_rust_lib_name, dev_path)
        if mod: return mod

    raise ImportError(f'Could not find Rust binary. Tried local dir and {dev_path}')

_libiso = _load_rust_pip_or_dev()
globals().update({k: v for k, v in vars(_libiso).items() if not k.startswith('__')})



## -- General helper functions

def ensure_uefi_bridge(cache_dir='.'):
    ''' Downloads the UEFI bridge image if it doesn't already exist '''

    local_path = os.path.join(cache_dir, UEFI_BRIDGE_NAME)
    
    if not os.path.exists(local_path):
        print(f'Downloading UEFI:NTFS bridge to {local_path}...')

        import urllib.request, urllib.error
        try:
            urllib.request.urlretrieve(UEFI_BRIDGE_DOWNLOAD_URL, local_path)
        except urllib.error.URLError as e:
            raise RuntimeError(f'Failed to download UEFI bridge: {e}')
            
    return local_path


def generate_dbx_rust_arrays(dbx_json_url: str = DBX_REVOCATION_URL, output_path = '../src/dbx.rs'):

    import urllib.request, urllib.error, json, inspect

    res = urllib.request.urlopen(dbx_json_url).read().decode()
    data = json.loads(res)

    flat_hashes = set()
    for arch, images in data.get('images', {}).items():
        for image in images:
            flat_hash = image.get('flatHash', '').strip().upper()
            flat_hashes.add(flat_hash)
    
    if '' in flat_hashes: flat_hashes.remove('')
    sorted_hashes = sorted(list(flat_hashes))

    with open(output_path, 'w') as f:

        f.write(f'// Generated by libiso.{inspect.currentframe().f_code.co_name}()\n')
        f.writelines('\n'.join(
'''
pub const TRUSTED_MS_CA_THUMBPRINTS: &[&str] = &[
    'AEFC5FBBBE055D8F8DAA585473499417AB5A5272', 
    '81AA6B3244C935BCE0D6628AF39827421E32497D',
    'A92902398E16C49778CD90F99E4F9AE17C55AF50',
    '13ADBF4309BD82709C8CD54F316ED522988A1BD4E', 
];
'''.split('\n')))
        f.write(f'\n\n// Via -\n')
        f.write(f'// {DBX_REVOCATION_URL}\n\n')
        f.write('pub const DBX_HASHES: &[&str] = &[\n')
        for h in sorted_hashes:
            f.write(f'''    '{h}',\n''')
        f.write('];\n')

    print(f'Extracted {len(sorted_hashes)} flat hashes to {output_path}')


def _progress_bar(written: int, total: int, prefix: str = 'Progress'):

    percent = (written / total) * 100 if total > 0 else 0
    bar_len = 40
    filled = int(bar_len * written / total) if total > 0 else 0
    bar = '█' * filled + '-' * (bar_len - filled)
    
    # \r resets the cursor to the beginning of the line to overwrite it
    sys.stdout.write(f'\rProgress: |{bar}| {percent:.1f}% ({written}/{total} bytes)')
    sys.stdout.flush()


## -- Python wrappers

def write_image_iso(
    image_path: str,
    device_path: str,
    has_large_file: bool,
    partition_scheme: str = 'gpt',
    uefi_ntfs_path: str = None,
    persistence_size_mb: int = None
):
    ext4_temp_path = None
    
    if persistence_size_mb:
        fd, ext4_temp_path = tempfile.mkstemp(suffix='.ext4')
        os.close(fd)

    try:
        return _libiso.write_image_iso(
            image_path,
            device_path,
            has_large_file,
            partition_scheme,
            uefi_ntfs_path,
            persistence_size_mb,
            ext4_temp_path
        )
    finally:
        if ext4_temp_path and os.path.exists(ext4_temp_path):
            os.remove(ext4_temp_path)


def burn_image(
    image_path: str, 
    device_path: str, 
    method: str = 'ISO',
    partition_scheme: str = None,     
    persistence_size_mb: int = None,
    verify_written: bool = False   
):

    if not os.path.exists(image_path):
        raise FileNotFoundError(f'Image not found: {image_path}')

    if (method := method.upper()) not in ('ISO', 'DD'):
        raise ValueError(f'Unknown method: {method}. Use iso or dd')

    if method == 'DD':
        print(f'Starting raw DD write from {image_path} to {device_path}...')
        stream = _libiso.write_image_dd(image_path, device_path, verify_written)
        
        phase = 'DD Write'
        highest_written = 0
        
        for written, total in stream:
            # Check if Rust has entered the verification loop
            if written < highest_written:
                phase = 'Verifying'
                print('\nWrite complete! Starting bit-for-bit verification...')
                highest_written = 0
                
            highest_written = written
            _progress_bar(written, total, prefix=phase)
            
        print(f'\n{phase} Complete!')

    if method == 'ISO':
        print(f'Inspecting ISO: {image_path}')
        stats = _libiso.inspect_image(image_path)
        has_large_file = stats.has_large_file
        
        if partition_scheme is None:
            # If we detect UEFI, use GPT. Otherwise, fallback to MBR.
            # Using getattr is a safe way to check properties without crashing!
            partition_scheme = 'GPT' if getattr(stats.boot_info, 'supports_uefi', False) else 'MBR'

        uefi_path = ensure_uefi_bridge() if has_large_file else None

        print(f'Starting ISO filesystem extraction ({partition_scheme.upper()}) to {device_path}...')       
        stream = write_image_iso(
            image_path, 
            device_path, 
            has_large_file, 
            partition_scheme, 
            uefi_path, 
            persistence_size_mb
        )

    for written, total in stream:
        _progress_bar(written, total)
            
    print(f'\n{method} burning complete!') 
    return


## --  TUI & Cross-Platform Input

# --- ANSI Escape Sequences ---
CLEAR_SCREEN = '\033[2J'
CURSOR_HOME = '\033[H'
HIDE_CURSOR = '\033[?25l'
SHOW_CURSOR = '\033[?25h'

# Colors
COLOR_RESET = '\033[0m'
COLOR_TITLE = '\033[1;36m'   # Bold Cyan
COLOR_SUCCESS = '\033[1;32m' # Bold Green
COLOR_WARNING = '\033[1;33m' # Bold Yellow
COLOR_DANGER = '\033[1;31m'  # Bold Red
COLOR_BAR = '\033[38;5;39m'  # Rich-style blueish bar
COLOR_SELECT = '\033[7m'     # Inverted colors for selection


def move_cursor(row: int, col: int) -> str:
    return f'\033[{row};{col}H'


def read_key_nonblocking() -> str:
    ''' Cross-platform non-blocking keystroke reader '''

    if os.name == 'nt':
        if msvcrt.kbhit():
            key = msvcrt.getch()
            if key in (b'\x00', b'\xe0'): # Special keys (arrows)
                key = msvcrt.getch()
                if key == b'H': return 'UP'
                if key == b'P': return 'DOWN'
            elif key == b'\r': return 'ENTER'
            elif key in (b'q', b'Q', b'\x1b'): return 'QUIT'
            return key.decode('utf-8', 'ignore')
        return None
    else:
        rlist, _, _ = select.select([sys.stdin], [], [], 0.05)
        if rlist:
            key = sys.stdin.read(1)
            if key == '\x1b': # Escape sequence
                rlist, _, _ = select.select([sys.stdin], [], [], 0.01)
                if rlist:
                    sys.stdin.read(1) # Skip '['
                    arr = sys.stdin.read(1)
                    if arr == 'A': return 'UP'
                    if arr == 'B': return 'DOWN'
                return 'QUIT' # Raw ESC
            elif key in ('\r', '\n'): return 'ENTER'
            elif key in ('q', 'Q'): return 'QUIT'
            return key
        return None


def draw_static_ui(drives: list, selected_idx: int, stats, mode: str, verify: bool):
    ''' Draws the interactive menu and ISO metadata '''

    sys.stdout.write(CLEAR_SCREEN + CURSOR_HOME)
    
    # Header
    sys.stdout.write(move_cursor(2, 4) + f'{COLOR_TITLE}╔══════════════════════════════════════════════════════════╗{COLOR_RESET}')
    sys.stdout.write(move_cursor(3, 4) + f'{COLOR_TITLE}║{COLOR_RESET}                    libiso USB Flasher                    {COLOR_TITLE}║{COLOR_RESET}')
    sys.stdout.write(move_cursor(4, 4) + f'{COLOR_TITLE}╚══════════════════════════════════════════════════════════╝{COLOR_RESET}')
    
    # ISO Inspection Stats
    iso_name = os.path.basename(stats.file_path)
    size_mb = stats.size_bytes / (1024 * 1024)
    boot_str = f'{COLOR_SUCCESS}Yes{COLOR_RESET}' if stats.boot_info.is_bootable else f'{COLOR_DANGER}No{COLOR_RESET}'
    win_str = f'{COLOR_SUCCESS}Yes{COLOR_RESET}' if stats.windows_info else 'No'
    
    sys.stdout.write(move_cursor(6, 6) + f'Source ISO : [ {iso_name} ] ({size_mb:.1f} MB)')
    sys.stdout.write(move_cursor(7, 6) + f'Bootable   : {boot_str} (Windows: {win_str}, ISOHybrid: {stats.is_isohybrid})')
    sys.stdout.write(move_cursor(8, 6) + f'Settings   : Mode: {mode} | Verify: {verify}')
    
    # Drive Selection
    sys.stdout.write(move_cursor(10, 6) + 'Select Target Device (Up/Down Arrows):')
    
    for i, drive in enumerate(drives):
        row = 12 + i
        prefix = ' > ' if i == selected_idx else '   '
        color = COLOR_SELECT if i == selected_idx else COLOR_RESET
        sys.stdout.write(move_cursor(row, 6) + f'{prefix}{color}[ {drive.display_name} ]{COLOR_RESET}')

    # Controls
    controls_row = 14 + len(drives)
    sys.stdout.write(move_cursor(controls_row, 6) + f'{COLOR_SUCCESS}[ ENTER to START ]{COLOR_RESET}    {COLOR_WARNING}[ q to QUIT ]{COLOR_RESET}')
    sys.stdout.flush()


def draw_progress(row: int, phase: str, written: int, total: int):

    width = 40
    percent = (written / total) if total > 0 else 0
    filled_chars = int(width * percent)
    
    bar = '█' * filled_chars + '░' * (width - filled_chars)
    # \033[K clears the rest of the line so text doesn't ghost
    sys.stdout.write(move_cursor(row, 6) + f'\033[K{COLOR_WARNING}{phase:<15}:{COLOR_RESET} {COLOR_BAR}|{bar}|{COLOR_RESET} {percent*100:5.1f}%')
    sys.stdout.flush()


def tui_burn_worker(ui_queue: queue.Queue, iso_path: str, device_path: str, mode: str, verify: bool, stats):
    ''' Background thread routing the configuration to the Rust backend '''
    
    try:
        highest_written = 0
        phase = 'Writing'
        
        if mode == 'DD':
            ui_queue.put(('PHASE', 'Raw DD Write'))
            stream = _libiso.write_image_dd(iso_path, device_path, verify)
        else:
            ui_queue.put(('PHASE', 'ISO Extraction'))
            has_large_file = stats.has_large_file
            
            # Auto-detect partition scheme
            partition_scheme = 'GPT' if getattr(stats.boot_info, 'supports_uefi', False) else 'MBR'
            uefi_path = ensure_uefi_bridge() if has_large_file else None
            
            stream = _libiso.write_image_iso(
                iso_path, device_path, has_large_file, 
                partition_scheme, uefi_path, None, None, verify
            )
        
        for written, total in stream:
            if written < highest_written:
                phase = 'Verifying Data'
                ui_queue.put(('PHASE', phase))
                highest_written = 0
                
            highest_written = written
            ui_queue.put(('PROGRESS', written, total))
            
        ui_queue.put(('DONE', 'Burn and Verification Complete!'))
    except Exception as e:
        ui_queue.put(('ERROR', str(e)))


def tui_loop(iso_path: str, mode: str, verify: bool):

    try:
        stats = _libiso.inspect_image(iso_path)
    except Exception as e:
        print(f'Error inspecting ISO: {e}')
        return

    drives = _libiso.list_removable_drives()
    if not drives:
        print('No removable USB drives detected! Please insert a drive and try again.')
        return

    fd = sys.stdin.fileno()
    if os.name != 'nt':
        old_settings = termios.tcgetattr(fd)
        tty.setraw(fd)
    
    selected_idx = 0
    ui_queue = queue.Queue()
    is_burning = False
    current_phase = 'Waiting'
    
    try:
        sys.stdout.write(HIDE_CURSOR)
        draw_static_ui(drives, selected_idx, stats, mode, verify)
        progress_row = 16 + len(drives)
        
        while True:
            # Process backend messages
            while not ui_queue.empty():
                msg = ui_queue.get()
                if msg[0] == 'PHASE':
                    current_phase = msg[1]
                elif msg[0] == 'PROGRESS':
                    draw_progress(progress_row, current_phase, msg[1], msg[2])
                elif msg[0] == 'DONE':
                    is_burning = False
                    sys.stdout.write(move_cursor(progress_row + 2, 6) + f'\033[K{COLOR_SUCCESS}{msg[1]}{COLOR_RESET}')
                    sys.stdout.flush()
                elif msg[0] == 'ERROR':
                    is_burning = False
                    sys.stdout.write(move_cursor(progress_row + 2, 6) + f'\033[K{COLOR_DANGER}Error: {msg[1]}{COLOR_RESET}')
                    sys.stdout.flush()

            # Handle Input
            key = read_key_nonblocking()
            if key == 'QUIT':
                break
            
            if not is_burning:
                if key == 'UP':
                    selected_idx = max(0, selected_idx - 1)
                    draw_static_ui(drives, selected_idx, stats, mode, verify)
                elif key == 'DOWN':
                    selected_idx = min(len(drives) - 1, selected_idx + 1)
                    draw_static_ui(drives, selected_idx, stats, mode, verify)
                elif key == 'ENTER':
                    is_burning = True
                    target_device = drives[selected_idx].device_path
                    
                    sys.stdout.write(move_cursor(progress_row + 2, 6) + '\033[K') # Clear msgs
                    threading.Thread(
                        target=tui_burn_worker, 
                        args=(ui_queue, iso_path, target_device, mode, verify, stats), 
                        daemon=True
                    ).start()
                    
            if os.name != 'nt': time.sleep(0.01) # Prevent CPU pegging on Unix

    finally:
        if os.name != 'nt':
            termios.tcsetattr(fd, termios.TCSADRAIN, old_settings)
        sys.stdout.write(SHOW_CURSOR)
        sys.stdout.write(move_cursor(20 + len(drives), 1)) 
        sys.stdout.flush()


if __name__ == '__main__':

    import argparse

    parser = argparse.ArgumentParser(description='libiso - Cross-platform USB image flasher')
    parser.add_argument('iso_path', type=str, help='Path to the source ISO file')
    parser.add_argument('--mode', type=str, choices=['ISO', 'DD'], default='ISO', help='Write method (ISO extraction or Raw DD)')
    parser.add_argument('--verify', action='store_true', help='Perform a byte-for-byte verification pass after writing')
    
    args = parser.parse_args()

    if not os.path.exists(args.iso_path):
        print(f'''Error: ISO file not found at '{args.iso_path}' ''')
        sys.exit(1)

    tui_loop(args.iso_path, args.mode, args.verify)