import os, sys, importlib.util, tempfile
from typing import Callable


UEFI_BRIDGE_NAME = 'uefi-ntfs.img'
UEFI_BRIDGE_DOWNLOAD_URL = f'https://raw.githubusercontent.com/pbatard/rufus/master/res/uefi/{UEFI_BRIDGE_NAME}'
DBX_REVOCATION_URL = 'https://raw.githubusercontent.com/microsoft/secureboot_objects/refs/heads/main/PreSignedObjects/DBX/dbx_info_msft_latest.json'


## -- Load Rust module

def _load_module(module_name: str, path: str):

    spec = importlib.util.spec_from_file_location(module_name, path)
    if spec and spec.loader:
        mod = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(mod)
        return mod
    return None


def _load_rust_pip_or_dev(_rust_lib_name: str = '_libiso', module_dev_path: str = None):
    
    # Wheel load (pip install)
    try:
        from . import _libiso
        return _libiso
    except ImportError:
        pass
    
    if os.name == 'nt':
        expected_file = f'{_rust_lib_name}.dll' 
    elif sys.platform == 'darwin':
        expected_file = f'lib{_rust_lib_name}.dylib'
    else:
        expected_file = f'lib{_rust_lib_name}.so'

    py_dir = __file__.replace('\\', '/').rsplit('/', 1)[0]
    root_dir = py_dir.rsplit('/', 1)[0]
    dev_path = module_dev_path or f'{root_dir}/target/release/{expected_file}'
    
    # Search local directory (for maturin develop)
    for file in os.listdir(py_dir):
        if ((file.startswith(f'lib{_rust_lib_name}') or file.startswith(_rust_lib_name)) 
                and file.endswith(('.so', '.pyd', '.dylib', '.dll'))):
            mod = _load_module(_rust_lib_name, f'{py_dir}/{file}')
            if mod: return mod
    
    # Maturin build in CI
    if os.path.exists(dev_path):
        mod = _load_module(_rust_lib_name, dev_path)
        if mod: return mod

    raise ImportError(f'Could not find Rust binary. Tried local dir and {dev_path}')

_libiso = _load_rust_pip_or_dev()
globals().update({k: v for k, v in vars(_libiso).items() if not k.startswith('__')})



## -- General helper functions

def ensure_uefi_bridge(cache_dir='.'):
    ''' Downloads the UEFI bridge image if it doesn't already exist '''

    local_path = os.path.join(cache_dir, UEFI_BRIDGE_NAME)
    
    if not os.path.exists(local_path):
        print(f'Downloading UEFI:NTFS bridge to {local_path}...')

        import urllib.request, urllib.error
        try:
            urllib.request.urlretrieve(UEFI_BRIDGE_DOWNLOAD_URL, local_path)
        except urllib.error.URLError as e:
            raise RuntimeError(f'Failed to download UEFI bridge: {e}')
            
    return local_path


def generate_dbx_rust_arrays(dbx_json_url: str = DBX_REVOCATION_URL, output_path = '../src/dbx.rs'):

    import urllib.request, urllib.error, json, inspect

    res = urllib.request.urlopen(dbx_json_url).read().decode()
    data = json.loads(res)

    flat_hashes = set()
    for arch, images in data.get('images', {}).items():
        for image in images:
            flat_hash = image.get('flatHash', '').strip().upper()
            flat_hashes.add(flat_hash)
    
    if '' in flat_hashes: flat_hashes.remove('')
    sorted_hashes = sorted(list(flat_hashes))

    with open(output_path, 'w') as f:

        f.write(f'// Generated by libiso.{inspect.currentframe().f_code.co_name}()\n')
        f.writelines('\n'.join(
'''
pub const TRUSTED_MS_CA_THUMBPRINTS: &[&str] = &[
    "AEFC5FBBBE055D8F8DAA585473499417AB5A5272", 
    "81AA6B3244C935BCE0D6628AF39827421E32497D",
    "A92902398E16C49778CD90F99E4F9AE17C55AF50",
    "13ADBF4309BD82709C8CD54F316ED522988A1BD4E", 
];
'''.split('\n')))
        f.write(f'\n\n// Via -\n')
        f.write(f'// {DBX_REVOCATION_URL}\n\n')
        f.write('pub const DBX_HASHES: &[&str] = &[\n')
        for h in sorted_hashes:
            f.write(f'    "{h}",\n')
        f.write('];\n')

    print(f'Extracted {len(sorted_hashes)} flat hashes to {output_path}')


def _progress_bar(written: int, total: int):

    percent = (written / total) * 100 if total > 0 else 0
    bar_len = 40
    filled = int(bar_len * written / total) if total > 0 else 0
    bar = '█' * filled + '-' * (bar_len - filled)
    
    # \r resets the cursor to the beginning of the line to overwrite it
    sys.stdout.write(f'\rProgress: |{bar}| {percent:.1f}% ({written}/{total} bytes)')
    sys.stdout.flush()


## -- Python wrappers

def write_image_iso(
    image_path: str,
    device_path: str,
    has_large_file: bool,
    partition_scheme: str = 'gpt',
    uefi_ntfs_path: str = None,
    persistence_size_mb: int = None
):
    ext4_temp_path = None
    
    if persistence_size_mb:
        fd, ext4_temp_path = tempfile.mkstemp(suffix=".ext4")
        os.close(fd)

    try:
        return _libiso.write_image_iso(
            image_path,
            device_path,
            has_large_file,
            partition_scheme,
            uefi_ntfs_path,
            persistence_size_mb,
            ext4_temp_path
        )
    finally:
        if ext4_temp_path and os.path.exists(ext4_temp_path):
            os.remove(ext4_temp_path)


def burn_image(
    image_path: str, 
    device_path: str, 
    method: str = 'ISO',
    partition_scheme: str = None,     
    persistence_size_mb: int = None   
):
    if not os.path.exists(image_path):
        raise FileNotFoundError(f'Image not found: {image_path}')

    if (method := method.upper()) not in ('ISO', 'DD'):
        raise ValueError(f'Unknown method: {method}. Use iso or dd')

    if method == 'DD':
        print(f'Starting raw DD write from {image_path} to {device_path}...')
        stream = _libiso.write_image_dd(image_path, device_path)
        
    if method == 'ISO':
        print(f'Inspecting ISO: {image_path}')
        stats = _libiso.inspect_image(image_path)
        has_large_file = stats.has_large_file
        
        if partition_scheme is None:
            # If we detect UEFI, use GPT. Otherwise, fallback to MBR.
            # Using getattr is a safe way to check properties without crashing!
            partition_scheme = 'GPT' if getattr(stats.boot_info, 'supports_uefi', False) else 'MBR'

        uefi_path = ensure_uefi_bridge() if has_large_file else None
        
        print(f'Starting ISO filesystem extraction ({partition_scheme.upper()}) to {device_path}...')       
        stream = write_image_iso(
            image_path, 
            device_path, 
            has_large_file, 
            partition_scheme, 
            uefi_path, 
            persistence_size_mb
        )

    for written, total in stream:
        _progress_bar(written, total)
            
    print(f'\n{method} burning complete!') 
    return
