import os, sys, importlib.util, tempfile
from typing import Callable

# TUI imports
import threading, queue, time

if sys.platform == 'win32':
    import msvcrt
    # import ctypes
    # from ctypes import wintypes
else:
    import termios, tty, select




UEFI_BRIDGE_NAME = 'uefi-ntfs.img'
UEFI_BRIDGE_DOWNLOAD_URL = f'https://raw.githubusercontent.com/pbatard/rufus/master/res/uefi/{UEFI_BRIDGE_NAME}'
DBX_REVOCATION_URL = 'https://raw.githubusercontent.com/microsoft/secureboot_objects/refs/heads/main/PreSignedObjects/DBX/dbx_info_msft_latest.json'


## -- Load Rust module

def _load_module(module_name: str, path: str):

    spec = importlib.util.spec_from_file_location(module_name, path)
    if spec and spec.loader:
        mod = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(mod)
        return mod
    return None


def _load_rust_pip_or_dev(_rust_lib_name: str = '_libiso', module_dev_path: str = None):
    
    # Wheel load (pip install)
    try:
        from . import _libiso
        return _libiso
    except ImportError:
        pass
    
    if os.name == 'nt':
        expected_file = f'{_rust_lib_name}.dll' 
    elif sys.platform == 'darwin':
        expected_file = f'lib{_rust_lib_name}.dylib'
    else:
        expected_file = f'lib{_rust_lib_name}.so'

    py_dir = __file__.replace('\\', '/').rsplit('/', 1)[0]
    root_dir = py_dir.rsplit('/', 1)[0]
    dev_path = module_dev_path or f'{root_dir}/target/release/{expected_file}'
    
    # Search local directory (for maturin develop)
    for file in os.listdir(py_dir):
        if ((file.startswith(f'lib{_rust_lib_name}') or file.startswith(_rust_lib_name)) 
                and file.endswith(('.so', '.pyd', '.dylib', '.dll'))):
            mod = _load_module(_rust_lib_name, f'{py_dir}/{file}')
            if mod: return mod
    
    # Maturin build in CI
    if os.path.exists(dev_path):
        mod = _load_module(_rust_lib_name, dev_path)
        if mod: return mod

    raise ImportError(f'Could not find Rust binary. Tried local dir and {dev_path}')

_libiso = _load_rust_pip_or_dev()
globals().update({k: v for k, v in vars(_libiso).items() if not k.startswith('__')})



## -- General helper functions

def ensure_uefi_bridge(cache_dir='.'):
    ''' Downloads the UEFI bridge image if it's not available '''

    local_path = os.path.join(cache_dir, UEFI_BRIDGE_NAME)
    
    if not os.path.exists(local_path):
        print(f'Downloading UEFI:NTFS bridge to {local_path}...')

        import urllib.request, urllib.error
        try:
            urllib.request.urlretrieve(UEFI_BRIDGE_DOWNLOAD_URL, local_path)
        except urllib.error.URLError as e:
            raise RuntimeError(f'Failed to download UEFI bridge: {e}')
            
    return local_path


def generate_dbx_rust_arrays(dbx_json_url: str = DBX_REVOCATION_URL, output_path = '../src/dbx.rs'):
    ''' Generates static arrays in Rust of revoked signatures, to allow fast verification '''

    import urllib.request, urllib.error, json, inspect

    res = urllib.request.urlopen(dbx_json_url).read().decode()
    data = json.loads(res)

    flat_hashes = set()
    for arch, images in data.get('images', {}).items():
        for image in images:
            flat_hash = image.get('flatHash', '').strip().upper()
            flat_hashes.add(flat_hash)
    
    if '' in flat_hashes: flat_hashes.remove('')
    sorted_hashes = sorted(list(flat_hashes))

    with open(output_path, 'w') as f:

        f.write(f'// -- Generated by libiso.{inspect.currentframe().f_code.co_name}()\n')
        f.writelines('\n'.join(
'''
pub const TRUSTED_MS_CA_THUMBPRINTS: &[&str] = &[
    'AEFC5FBBBE055D8F8DAA585473499417AB5A5272', 
    '81AA6B3244C935BCE0D6628AF39827421E32497D',
    'A92902398E16C49778CD90F99E4F9AE17C55AF50',
    '13ADBF4309BD82709C8CD54F316ED522988A1BD4E', 
];
'''.split('\n')))
        f.write(f'\n\n// Via -\n')
        f.write(f'// {DBX_REVOCATION_URL}\n\n')
        f.write('pub const DBX_HASHES: &[&str] = &[\n')
        for h in sorted_hashes:
            f.write(f'''    '{h}',\n''')
        f.write('];\n')

    print(f'Extracted {len(sorted_hashes)} flat hashes to {output_path}')


def _progress_bar(written: int, total: int, prefix: str = 'Progress'):

    percent = (written / total) * 100 if total > 0 else 0
    bar_len = 40
    filled = int(bar_len * written / total) if total > 0 else 0
    bar = '█' * filled + '-' * (bar_len - filled)
    
    # \r resets the cursor to the beginning of the line to overwrite it
    sys.stdout.write(f'\rProgress: |{bar}| {percent:.1f}% ({written}/{total} bytes)')
    sys.stdout.flush()


## -- Python wrappers

def write_image_iso(
    image_path: str,
    device_path: str,
    has_large_file: bool,
    partition_scheme: str = 'gpt',
    uefi_ntfs_path: str = None,
    persistence_size_mb: int = None
):
    ''' To avoid using the tempfile crate, which pulls windows-sys, we use a Python wrapper 
        and utilize it's built in tempfile
    '''

    ext4_temp_path = None
    
    if persistence_size_mb:
        fd, ext4_temp_path = tempfile.mkstemp(suffix='.ext4')
        os.close(fd)

    try:
        return _libiso.write_image_iso(
            image_path, device_path, has_large_file, partition_scheme, uefi_ntfs_path, persistence_size_mb, ext4_temp_path
        )
    finally:
        if ext4_temp_path and os.path.exists(ext4_temp_path):
            os.remove(ext4_temp_path)


def burn_image(
    image_path: str, 
    device_path: str, 
    method: str = 'ISO',
    partition_scheme: str = None,     
    persistence_size_mb: int = None,
    verify_written: bool = False   
):
    ''' High level wrapper for libiso's burning logic '''

    if not os.path.exists(image_path):
        raise FileNotFoundError(f'Image not found: {image_path}')

    if (method := method.upper()) not in ('ISO', 'DD'):
        raise ValueError(f'Unknown method: {method}. Use iso or dd')

    if method == 'DD':
        print(f'Starting raw DD write from {image_path} to {device_path}...')
        stream = _libiso.write_image_dd(image_path, device_path, verify_written)
        
        phase = 'DD Write'
        highest_written = 0
        
        for written, total in stream:
            # Check if Rust has entered the verification loop
            if written < highest_written:
                phase = 'Verifying'
                print('\nWrite complete! Starting bit-for-bit verification...')
                highest_written = 0
                
            highest_written = written
            _progress_bar(written, total, prefix=phase)
            
        print(f'\n{phase} Complete!')

    if method == 'ISO':
        print(f'Inspecting ISO: {image_path}')
        stats = _libiso.inspect_image(image_path)
        has_large_file = stats.has_large_file
        
        if partition_scheme is None:
            # If we detect UEFI, use GPT. Otherwise, fallback to MBR.
            # Using getattr is a safe way to check properties without crashing!
            partition_scheme = 'GPT' if getattr(stats.boot_info, 'supports_uefi', False) else 'MBR'

        uefi_path = ensure_uefi_bridge() if has_large_file else None

        print(f'Starting ISO filesystem extraction ({partition_scheme.upper()}) to {device_path}...')       
        stream = write_image_iso(
            image_path, 
            device_path, 
            has_large_file, 
            partition_scheme, 
            uefi_path, 
            persistence_size_mb
        )

    for written, total in stream:
        _progress_bar(written, total)
            
    print(f'\n{method} burning complete!') 
    return


## --  TUI & Cross-Platform Input

# --- ANSI Escape Sequences ---
CLEAR_SCREEN = '\033[2J'
CURSOR_HOME = '\033[H'
HIDE_CURSOR = '\033[?25l'
SHOW_CURSOR = '\033[?25h'

# Colors
COLOR_RESET = '\033[0m'
COLOR_TITLE = '\033[1;36m'   # Bold Cyan
COLOR_SUCCESS = '\033[1;32m' # Bold Green
COLOR_WARNING = '\033[1;33m' # Bold Yellow
COLOR_DANGER = '\033[1;31m'  # Bold Red
COLOR_BAR = '\033[38;5;39m'  # Rich-style blueish bar
COLOR_SELECT = '\033[7m'     # Inverted colors for selection
COLOR_DIM = '\033[2m'        # Dim text for inactive steps


def move_cursor(row: int, col: int) -> str:
    return f'\033[{row};{col}H'


def read_key_nonblocking() -> str:
    ''' Cross-platform non-blocking keystroke reader. '''

    if os.name == 'nt':
        # Use kbhit() to prevent getwch() from freezing the UI
        if msvcrt.kbhit():
            key = msvcrt.getwch()
            # Catch special keys (arrows)
            if key in ('\x00', '\xe0'): 
                key += msvcrt.getwch()
                if key.endswith('H'): return 'UP'
                if key.endswith('P'): return 'DOWN'
            elif key == '\r': return 'ENTER'
            elif key in ('q', 'Q', '\x1b'): return 'QUIT'
            elif key in ('y', 'Y'): return 'CONFIRM_YES'
            elif key in ('n', 'N'): return 'CONFIRM_NO'
            return key
        return None
    else:
        # Use select to prevent os.read from freezing the UI
        rlist, _, _ = select.select([0], [], [], 0.05)
        if rlist:
            seq = os.read(0, 32).decode('utf-8', 'ignore')
            
            if seq == '\x1b[A': return 'UP'
            if seq == '\x1b[B': return 'DOWN'
            if seq in ('\r', '\n'): return 'ENTER'
            if seq in ('q', 'Q', '\x1b'): return 'QUIT'
            if seq in ('y', 'Y'): return 'CONFIRM_YES'
            if seq in ('n', 'N'): return 'CONFIRM_NO'
            return seq
        return None


def draw_wizard_ui(
    iso_name: str, 
    drives: list, 
    step: int, 
    sel_drive: int, 
    sel_mode: int, 
    sel_verify: int, 
    stats
):
    ''' Draws the sequential configuration wizard '''
    sys.stdout.write(CLEAR_SCREEN + CURSOR_HOME)
    
    # --- Header ---
    sys.stdout.write(move_cursor(2, 4) + f'{COLOR_TITLE}╔══════════════════════════════════════════════════════════╗{COLOR_RESET}')
    sys.stdout.write(move_cursor(3, 4) + f'{COLOR_TITLE}║{COLOR_RESET}                    libiso USB Flasher                    {COLOR_TITLE}║{COLOR_RESET}')
    sys.stdout.write(move_cursor(4, 4) + f'{COLOR_TITLE}╚══════════════════════════════════════════════════════════╝{COLOR_RESET}')
    
    size_mb = stats.size_bytes / (1024 * 1024)
    boot_str = f'{COLOR_SUCCESS}Yes{COLOR_RESET}' if stats.boot_info.is_bootable else f'{COLOR_DANGER}No{COLOR_RESET}'
    
    sys.stdout.write(move_cursor(6, 6) + f'Source ISO : [ {iso_name} ] ({size_mb:.1f} MB)')
    sys.stdout.write(move_cursor(7, 6) + f'Bootable   : {boot_str}')
    
    row = 9
    
    # --- Step 1: Drive Selection ---
    color = COLOR_TITLE if step == 0 else (COLOR_RESET if step > 0 else COLOR_DIM)
    sys.stdout.write(move_cursor(row, 6) + f'{color}[Step 1] Select Target Device:{COLOR_RESET}')
    row += 1
    
    if step == 0:
        for i, drive in enumerate(drives):
            prefix = ' > ' if i == sel_drive else '   '
            item_color = COLOR_SELECT if i == sel_drive else COLOR_RESET
            sys.stdout.write(move_cursor(row, 6) + f'{prefix}{item_color}[ {drive.display_name} ]{COLOR_RESET}')
            row += 1
    else:
        sys.stdout.write(move_cursor(row, 6) + f'    [ {drives[sel_drive].display_name} ]')
        row += 1
        
    row += 1

    # --- Step 2: Mode Selection ---
    modes = ['ISO - Extract files to FAT32/exFAT', 'DD - Raw sector-by-sector clone']
    color = COLOR_TITLE if step == 1 else (COLOR_RESET if step > 1 else COLOR_DIM)
    sys.stdout.write(move_cursor(row, 6) + f'{color}[Step 2] Select Write Mode:{COLOR_RESET}')
    row += 1
    
    if step == 1:
        for i, m in enumerate(modes):
            prefix = ' > ' if i == sel_mode else '   '
            item_color = COLOR_SELECT if i == sel_mode else COLOR_RESET
            sys.stdout.write(move_cursor(row, 6) + f'{prefix}{item_color}[ {m} ]{COLOR_RESET}')
            row += 1
    elif step > 1:
        sys.stdout.write(move_cursor(row, 6) + f'    [ {modes[sel_mode]} ]')
        row += 1
        
    row += 1

    # --- Step 3: Verify Selection ---
    verifies = ['No - Faster', 'Yes - Cryptographic byte-for-byte check']
    color = COLOR_TITLE if step == 2 else (COLOR_RESET if step > 2 else COLOR_DIM)
    sys.stdout.write(move_cursor(row, 6) + f'{color}[Step 3] Verify Data After Write?{COLOR_RESET}')
    row += 1
    
    if step == 2:
        for i, v in enumerate(verifies):
            prefix = ' > ' if i == sel_verify else '   '
            item_color = COLOR_SELECT if i == sel_verify else COLOR_RESET
            sys.stdout.write(move_cursor(row, 6) + f'{prefix}{item_color}[ {v} ]{COLOR_RESET}')
            row += 1
    elif step > 2:
        sys.stdout.write(move_cursor(row, 6) + f'    [ {verifies[sel_verify]} ]')
        row += 1
        
    row += 2

    # --- Step 4: Confirmation ---
    if step == 3:
        sys.stdout.write(move_cursor(row, 6) + f'{COLOR_DANGER}╔════════════════════════════════════════════════════════╗{COLOR_RESET}')
        sys.stdout.write(move_cursor(row+1, 6) + f'{COLOR_DANGER}║ WARNING: ALL DATA ON THE TARGET DEVICE WILL BE ERASED! ║{COLOR_RESET}')
        sys.stdout.write(move_cursor(row+2, 6) + f'{COLOR_DANGER}╚════════════════════════════════════════════════════════╝{COLOR_RESET}')
        sys.stdout.write(move_cursor(row+4, 6) + f'Are you absolutely sure? Type {COLOR_SUCCESS}[y]{COLOR_RESET} to start or {COLOR_WARNING}[n]{COLOR_RESET} to cancel.')

    # --- Footer Controls ---
    if step < 3:
        sys.stdout.write(move_cursor(22, 6) + f'{COLOR_SUCCESS}[ ENTER to Continue ]{COLOR_RESET}    {COLOR_WARNING}[ q to QUIT ]{COLOR_RESET}')
    sys.stdout.flush()


def draw_progress(row: int, phase: str, written: int, total: int):

    width = 40
    percent = (written / total) if total > 0 else 0
    filled_chars = int(width * percent)
    
    bar = '█' * filled_chars + '░' * (width - filled_chars)
    sys.stdout.write(move_cursor(row, 6) + f'\033[K{COLOR_WARNING}{phase:<15}:{COLOR_RESET} {COLOR_BAR}|{bar}|{COLOR_RESET} {percent*100:5.1f}%')
    sys.stdout.flush()


def tui_burn_worker(ui_queue: queue.Queue, iso_path: str, device_path: str, mode: str, verify: bool, stats):
    
    try:
        highest_written = 0
        phase = 'Writing'
        
        if mode == 'DD':
            ui_queue.put(('PHASE', 'Raw DD Write'))
            stream = _libiso.write_image_dd(iso_path, device_path, verify)
        else:
            ui_queue.put(('PHASE', 'ISO Extraction'))
            has_large_file = stats.has_large_file
            partition_scheme = 'GPT' if getattr(stats.boot_info, 'supports_uefi', False) else 'MBR'
            uefi_path = ensure_uefi_bridge() if has_large_file else None
            
            stream = _libiso.write_image_iso(
                iso_path, device_path, has_large_file, 
                partition_scheme, uefi_path, None, None, verify
            )
        
        for written, total in stream:
            if written < highest_written:
                phase = 'Verifying Data'
                ui_queue.put(('PHASE', phase))
                highest_written = 0
                
            highest_written = written
            ui_queue.put(('PROGRESS', written, total))
            
        ui_queue.put(('DONE', 'Burn and Verification Complete!'))
    except Exception as e:
        ui_queue.put(('ERROR', str(e)))


def tui_loop(iso_path: str):

    try:
        stats = _libiso.inspect_image(iso_path)
    except Exception as e:
        print(f'Error inspecting ISO: {e}')
        return

    drives = _libiso.list_removable_drives()
    if not drives:
        print('No removable USB drives detected! Please insert a drive and try again.')
        return

    fd = sys.stdin.fileno()
    if os.name != 'nt':
        old_settings = termios.tcgetattr(fd)
        tty.setraw(fd)
    
    # State machine variables
    step = 0  # 0: Drive, 1: Mode, 2: Verify, 3: Confirm, 4: Burning
    sel_drive = 0
    sel_mode = 0
    sel_verify = 0
    
    ui_queue = queue.Queue()
    current_phase = 'Waiting'
    
    try:
        sys.stdout.write(HIDE_CURSOR)
        draw_wizard_ui(os.path.basename(iso_path), drives, step, sel_drive, sel_mode, sel_verify, stats)
        
        while True:
            # Process backend messages if burning
            while not ui_queue.empty():
                msg = ui_queue.get()
                progress_row = 20 # Fixed row for progress bar during burn
                if msg[0] == 'PHASE':
                    current_phase = msg[1]
                elif msg[0] == 'PROGRESS':
                    draw_progress(progress_row, current_phase, msg[1], msg[2])
                elif msg[0] == 'DONE':
                    step = 5 # Done
                    sys.stdout.write(move_cursor(progress_row + 2, 6) + f'\033[K{COLOR_SUCCESS}Success: {msg[1]}{COLOR_RESET}')
                    sys.stdout.flush()
                elif msg[0] == 'ERROR':
                    step = 5 # Done (Error)
                    sys.stdout.write(move_cursor(progress_row + 2, 6) + f'\033[K{COLOR_DANGER}Error: {msg[1]}{COLOR_RESET}')
                    sys.stdout.flush()

            # Handle Input
            key = read_key_nonblocking()
            if key == 'QUIT':
                break
            
            if step < 4: # If not burning yet
                if key == 'UP':
                    if step == 0: sel_drive = max(0, sel_drive - 1)
                    elif step == 1: sel_mode = max(0, sel_mode - 1)
                    elif step == 2: sel_verify = max(0, sel_verify - 1)
                    draw_wizard_ui(os.path.basename(iso_path), drives, step, sel_drive, sel_mode, sel_verify, stats)
                
                elif key == 'DOWN':
                    if step == 0: sel_drive = min(len(drives) - 1, sel_drive + 1)
                    elif step == 1: sel_mode = min(1, sel_mode + 1)
                    elif step == 2: sel_verify = min(1, sel_verify + 1)
                    draw_wizard_ui(os.path.basename(iso_path), drives, step, sel_drive, sel_mode, sel_verify, stats)
                
                elif key == 'ENTER' and step < 3:
                    step += 1
                    draw_wizard_ui(os.path.basename(iso_path), drives, step, sel_drive, sel_mode, sel_verify, stats)
                
                elif step == 3: # Confirmation Step
                    if key == 'CONFIRM_NO':
                        step = 0 # Reset to beginning
                        draw_wizard_ui(os.path.basename(iso_path), drives, step, sel_drive, sel_mode, sel_verify, stats)
                    elif key == 'CONFIRM_YES':
                        step = 4 # Burning State
                        target_device = drives[sel_drive].device_path
                        mode_str = 'ISO' if sel_mode == 0 else 'DD'
                        verify_bool = sel_verify == 1
                        
                        sys.stdout.write(move_cursor(18, 6) + '\033[0J') # Clear confirmation prompt
                        sys.stdout.write(move_cursor(20, 6) + f'{COLOR_TITLE}Starting deployment...{COLOR_RESET}')
                        sys.stdout.flush()
                        
                        threading.Thread(
                            target=tui_burn_worker, 
                            args=(ui_queue, iso_path, target_device, mode_str, verify_bool, stats), 
                            daemon=True
                        ).start()
                    
            if os.name != 'nt': time.sleep(0.01)

    finally:
        if os.name != 'nt':
            termios.tcsetattr(fd, termios.TCSADRAIN, old_settings)
        sys.stdout.write(SHOW_CURSOR)
        sys.stdout.write(move_cursor(24, 1)) 
        sys.stdout.flush()


if __name__ == '__main__':

    import argparse

    parser = argparse.ArgumentParser(description='libiso - Cross-platform USB image flasher')
    parser.add_argument('iso_path', type=str, help='Path to the source ISO file')
    args = parser.parse_args()

    if not os.path.exists(args.iso_path):
        print(f'''Error: ISO file not found at '{args.iso_path}' ''')
        sys.exit(1)

    tui_loop(args.iso_path)